const $=s=>document.querySelector(s), money=n=>'S/ '+Number(n).toLocaleString('es-PE',{minimumFractionDigits:2,maximumFractionDigits:2});
const fresh={users:{cliente:{name:'Cliente Demo',balance:1250,debt:0,next:0,moves:[{type:'Depósito inicial',amount:1250,status:'Validado',date:'05/09/2026'}]}},requests:[]};
let db=JSON.parse(localStorage.getItem('creditoAhorro')||JSON.stringify(fresh)); let session=null;
function save(){localStorage.setItem('creditoAhorro',JSON.stringify(db))} function today(){return new Date().toLocaleDateString('es-PE')}
function login(){const u=$('#loginUser').value.trim(),p=$('#loginPass').value;if(u==='cliente'&&p==='1234'){session={role:'client',data:db.users.cliente}}else if(u==='admin'&&p==='admin'){session={role:'admin',data:{name:'Administrador'}}}else return alert('Usuario o contraseña incorrectos');$('#login').hidden=true;$('#system').hidden=false;$('#userbar').hidden=false;$('#userName').textContent=session.data.name;$('#title').textContent='Hola, '+session.data.name;$('#subtitle').textContent=session.role==='admin'?'Panel de administración':'Panel de cliente';$('#clientView').hidden=session.role!=='client';$('#adminView').hidden=session.role!=='admin';render()}
function logout(){location.reload()} function tab(id){document.querySelectorAll('.page').forEach(x=>x.hidden=true);$('#'+id).hidden=false;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));render()}
function addMove(type,amount,status){session.data.moves.push({type,amount,status,date:today()});save();render()}
function render(){if(session?.role==='client'){const c=session.data;$('#balance').textContent=money(c.balance);$('#savingBalance').textContent=money(c.balance);$('#debt').textContent=money(c.debt);$('#nextPay').textContent=money(c.next);const rows=c.moves.slice().reverse().map(m=>`<div class="row"><span><b>${m.type}</b><br><small>${m.date} · <span class="${m.status==='Validado'?'ok':m.status==='Pendiente'?'pending':'danger'}">${m.status}</span></small></span><b>${money(m.amount)}</b></div>`).join('')||'<p>No hay movimientos.</p>';$('#recent').innerHTML=rows.slice(0,3);$('#historyList').innerHTML=rows;$('#creditInfo').innerHTML=c.debt?`<p>Deuda pendiente: <b>${money(c.debt)}</b></p><p>Próxima cuota: <b>${money(c.next)}</b></p>`:'<p>No tienes un crédito activo.</p>'}else if(session?.role==='admin')renderAdmin()}
function openDeposit(){modal('Registrar depósito',`<p>El depósito quedará registrado en tu ahorro.</p><input id="amt" type="number" min="1" placeholder="Monto en soles"><button class="primary" onclick="deposit()">Registrar depósito</button>`)}
function deposit(){const n=+$('#amt').value;if(n<=0)return alert('Ingresa un monto válido');session.data.balance+=n;addMove('Depósito',n,'Validado');closeModal();alert('Depósito registrado correctamente.')}
function openWithdraw(){modal('Solicitar retiro',`<p>Saldo disponible: <b>${money(session.data.balance)}</b></p><input id="amt" type="number" min="1" placeholder="Monto"><input id="dest" placeholder="Cuenta, Yape o medio de retiro"><button class="primary" onclick="withdraw()">Enviar solicitud</button>`)}
function withdraw(){const n=+$('#amt').value,d=$('#dest').value.trim();if(n<=0||n>session.data.balance||!d)return alert('Verifica el monto y el destino.');session.data.balance-=n;db.requests.push({id:Date.now(),type:'Retiro',amount:n,dest:d,status:'Pendiente',date:today()});addMove('Solicitud de retiro',-n,'Pendiente');closeModal();alert('Solicitud enviada al administrador.')}
function openTransfer(){modal('Transferir dinero',`<p>Saldo disponible: <b>${money(session.data.balance)}</b></p><input id="amt" type="number" min="1" placeholder="Monto"><input id="dest" placeholder="Código del cliente destinatario"><button class="primary" onclick="transfer()">Confirmar transferencia</button>`)}
function transfer(){const n=+$('#amt').value,d=$('#dest').value.trim();if(n<=0||n>session.data.balance||!d)return alert('Verifica el monto y destinatario.');session.data.balance-=n;addMove('Transferencia a '+d,-n,'Validado');closeModal();alert('Transferencia registrada.')}
function requestCredit(){const n=+$('#creditAmount').value,t=+$('#creditTerm').value;if(n<100)return alert('El monto mínimo es S/ 100.');db.requests.push({id:Date.now(),type:'Crédito',amount:n,term:t,status:'Pendiente',date:today()});save();$('#creditAmount').value='';alert('Solicitud de crédito enviada.');render()}
function renderAdmin(){const r=db.requests,p=r.filter(x=>x.status==='Pendiente');$('#aCredits').textContent=p.filter(x=>x.type==='Crédito').length;$('#aWithdrawals').textContent=p.filter(x=>x.type==='Retiro').length;$('#adminList').innerHTML=p.length?p.map(x=>`<div class="row"><span><b>${x.type}</b> · ${money(x.amount)}<br><small>${x.date} · ${x.dest||x.term+' cuotas'}</small></span><button onclick="approve(${x.id})">Aprobar</button></div>`).join(''):'<p>No hay operaciones pendientes.</p>';$('#adminSummary').innerHTML=`<p>Clientes registrados: <b>${Object.keys(db.users).length}</b></p><p>Solicitudes totales: <b>${r.length}</b></p><p>Saldo del cliente demo: <b>${money(db.users.cliente.balance)}</b></p>`}
function approve(id){const r=db.requests.find(x=>x.id===id);if(!r)return;r.status='Aprobado';save();renderAdmin();alert('Operación aprobada. Para producción, esta aprobación debe ejecutar el movimiento mediante un backend seguro.')}
function modal(t,b){$('#modalTitle').textContent=t;$('#modalBody').innerHTML=b;$('#modal').hidden=false}function closeModal(){$('#modal').hidden=true}
render();
