const API_BASE=localStorage.getItem('contapro_api')||'http://localhost:3000';
const view=document.querySelector('#view'), userEl=document.querySelector('#user');
async function api(path, options={}){const r=await fetch(API_BASE+path,options); if(!r.ok) throw new Error('API '+r.status); return r.json();}
userEl.textContent=localStorage.getItem('contapro_user')||'demo@contapro.pe';
const data={empresas:[['Comercial Demo S.A.C.','RUC 20600000001','Activo'],['Servicios Andinos E.I.R.L.','RUC 20600000002','Activo'],['Inversiones Norte S.A.C.','RUC 20600000003','Pendiente']],clientes:[['Cliente Ejemplo S.A.C.','RUC 20611111111','S/ 4,500'],['Juan Pérez','DNI 70123456','S/ 1,280'],['Distribuidora Central','RUC 20522222222','S/ 8,740']],compras:[['FAC-001-004521','Proveedor Andino','S/ 2,850','10/09/2026'],['FAC-001-004522','Servicios SAC','S/ 1,420','09/09/2026'],['FAC-001-004523','Oficinas Perú','S/ 680','08/09/2026']],ventas:[['B001-000154','Cliente Ejemplo','S/ 3,250','10/09/2026'],['F001-000982','Distribuidora Central','S/ 7,800','09/09/2026'],['F001-000981','Comercial Sur','S/ 4,150','08/09/2026']]};
function table(headers,rows){return `<table class="table"><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((x,i)=>`<td>${i===r.length-1&&['Activo','Pendiente'].includes(x)?`<span class="tag">${x}</span>`:x}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
function inicio(){view.innerHTML=`<div class="dash-title"><div><h1>Resumen</h1><p>Visión general de tu estudio contable.</p></div><button class="btn" onclick="alert('Nueva empresa: demo')">+ Nueva empresa</button></div><div class="grid4"><div class="stat"><small>Empresas</small><strong>8</strong></div><div class="stat"><small>Ventas del mes</small><strong>S/ 128,450</strong></div><div class="stat"><small>Compras del mes</small><strong>S/ 64,280</strong></div><div class="stat"><small>Resultado</small><strong>S/ 32,760</strong></div></div><div class="panel"><h3>Ventas últimos meses</h3><div class="chart">${[45,58,50,72,65,88,78].map(h=>`<i style="height:${h}%"></i>`).join('')}</div></div><div class="panel"><h3>Actividad reciente</h3>${table(['Documento','Descripción','Importe','Fecha'],data.ventas)}</div>`}
function list(type,title,headers){view.innerHTML=`<div class="dash-title"><h1>${title}</h1><button class="btn" onclick="alert('Formulario de ${title}: demo')">+ Agregar</button></div><div class="panel"><div class="toolbar"><input placeholder="Buscar..."><button class="btn small">Buscar</button></div>${table(headers,data[type])}</div>`}
function generic(title,text){view.innerHTML=`<div class="dash-title"><h1>${title}</h1><button class="btn" onclick="alert('Acción de demo')">+ Nuevo</button></div><div class="notice">${text}</div><div class="cards-mini"><div class="panel"><h3>Resumen</h3><p>Información centralizada para tu gestión.</p><strong>Actualizado hoy</strong></div><div class="panel"><h3>Procesos</h3><p>Registra y consulta operaciones desde este módulo.</p><strong>Operativo</strong></div><div class="panel"><h3>Reportes</h3><p>Genera información para el análisis y toma de decisiones.</p><strong>Disponible</strong></div></div>`}
function render(v){if(v==='inicio')inicio();else if(v==='empresas')list('empresas','Empresas',['Empresa','Identificación','Estado']);else if(v==='clientes')list('clientes','Clientes',['Cliente','Documento','Saldo']);else if(v==='compras')list('compras','Compras',['Comprobante','Proveedor','Importe','Fecha']);else if(v==='ventas')list('ventas','Ventas',['Comprobante','Cliente','Importe','Fecha']);else if(v==='contabilidad')generic('Contabilidad','Administra el plan contable, asientos, libro diario, mayor y balances.');else if(v==='reportes')generic('Reportes','Consulta estados financieros, indicadores y reportes de gestión.');else if(v==='tributario')generic('Módulo tributario','Centraliza información para el control de obligaciones tributarias.');
else if(v==='sunat')sunat();
else generic('Configuración','Administra datos de empresa, usuarios y preferencias.')}
async function sunat(){
  view.innerHTML=`<div class="dash-title"><div><h1>Conexión SUNAT</h1><p>Estado de la integración del servidor.</p></div><button class="btn" id="checkSunat">Comprobar conexión</button></div>
  <div class="panel"><div id="sunatBox">Consultando backend...</div></div>
  <div class="panel"><h3>Comprobante de prueba</h3><p>Genera un comprobante local para verificar la comunicación frontend → backend. No lo envía a SUNAT.</p><button class="btn" id="demoInvoice">Crear comprobante demo</button><pre id="demoOut"></pre></div>`;
  const box=document.querySelector('#sunatBox');
  try{const s=await api('/api/sunat/status');box.innerHTML=`<p><b>Backend:</b> conectado</p><p><b>Configurado:</b> ${s.configured?'Sí':'No'}</p><p><b>Ambiente:</b> ${s.environment}</p><p><b>Endpoint CPE:</b> ${s.cpeEndpoint}</p>`}
  catch(e){box.innerHTML='<p>⚠️ No se pudo conectar al backend. Inicia el servidor y revisa la URL de API.</p>'}
  document.querySelector('#checkSunat').onclick=sunat;
  document.querySelector('#demoInvoice').onclick=async()=>{try{const x=await api('/api/comprobantes/demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({total:118})});document.querySelector('#demoOut').textContent=JSON.stringify(x,null,2)}catch(e){document.querySelector('#demoOut').textContent=e.message}};
}
document.querySelectorAll('.nav[data-view]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.view)});
document.querySelector('#logout').onclick=()=>{localStorage.removeItem('contapro_user');location.href='login.html'};document.querySelector('#menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');render('inicio');
